name: party_app_ui
description: Party app UI


version: 1.0.0+1

environment:
  sdk: ">=2.11.1"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  simple_animations: ^1.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
